-intstyle "ise" -incremental -lib "unisims_ver" -lib "unimacro_ver" -lib "xilinxcorelib_ver" -o "C:/ise/Adder_time3/test_isim_beh.exe" -prj "C:/ise/Adder_time3/test_beh.prj" "work.test" "work.glbl" 
